# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47a7a65c506118602e7b9866e3462aeb42f5b3dab02468d336fab5164f0dc6ed8174e6cc8bd584e14a2b2640ca797937bcfa005d443724acfaaefa58b1990e91

test:
  secret_key_base: b0b137a8aceb518ded056e8c39e2c10166d8f2d9129ce2ab851bf8c90f04edca6958ad7b119b9bfbcc0f3d5fde2e43c77da76e1ffaedd571f013d368a80e2a49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
